# Generated by Django 6.0.3 on 2026-03-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseroadmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmapstep',
            name='course',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='RoadmapStep',
        ),
    ]
